version: '3.7'

services:
  cache:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    env_file:
      - .env.prod

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  web:
    env_file:
      - .env.prod
    build: .
    ports:
      - "5000:8001"
    depends_on:
      - cache
      - postgres
    command: >
      sh -c 
      "gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:8001"


volumes:
  redis_data:
  postgres_data:

